# 2013-10-30T14:07:41 by juan .covio.yml Continuous Integration by Ninja-IDE
violations:
    pep8: pep8 . --exclude="*migrations*,*settings*,*components*,*docs*"
    sloccount: sloccount .
    # py_unittest: cat test_result    # enable when we got Tests
    # coverage: coverage report    # enable when we got Tests
    pip_review:
        command: pip-review
        nofail: true
    jslint: jslint *.js
